// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElForm: typeof import('element-plus/es/el-form')['ElForm']
  const ElTree: typeof import('element-plus/es/el-tree')['ElTree']
}
export {}
